#!/usr/bin/env python3
"""Build BGC atlas tables from DeepBGC metadata and BLASTp hits.

Inputs are generated by the upstream genome/DeepBGC/BLAST workflow:

- all_genes.csv: gene-to-BGC mapping exported from detected BGCs
- blast_raw_results.tsv: BLASTp hits against MIBiG proteins with columns
  gene_id, mibig_id, pident, qcovs, evalue
- all_bgcs_combined.csv: BGC-level DeepBGC metadata

Outputs match the atlas files used downstream by the paper analysis pipeline.
Large output tables are intentionally not committed to Git.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--genes", default="all_genes.csv", help="Gene-to-BGC table")
    parser.add_argument(
        "--blast", default="blast_raw_results.tsv", help="Raw BLASTp TSV without header"
    )
    parser.add_argument(
        "--bgcs", default="all_bgcs_combined.csv", help="BGC-level DeepBGC metadata"
    )
    parser.add_argument("--output-dir", default=".", help="Directory for output CSV files")
    parser.add_argument("--min-query-coverage", type=float, default=50.0)
    parser.add_argument("--known-identity-threshold", type=float, default=40.0)
    parser.add_argument("--min-deepbgc-score", type=float, default=0.7)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print("Loading data...")
    genes_df = pd.read_csv(args.genes)
    blast_cols = ["gene_id", "mibig_id", "pident", "qcovs", "evalue"]
    blast_df = pd.read_csv(args.blast, sep="\t", names=blast_cols)
    bgc_metadata = pd.read_csv(args.bgcs)

    valid_blast = blast_df[blast_df["qcovs"] >= args.min_query_coverage]

    print("Merging gene annotations with BLAST hits...")
    merged_genes = pd.merge(genes_df, valid_blast, on="gene_id", how="left")
    merged_genes["pident"] = merged_genes["pident"].fillna(0)
    merged_genes["mibig_id"] = merged_genes["mibig_id"].fillna("No Match")
    merged_genes.to_csv(output_dir / "master_gene_annotations.csv", index=False)

    print("Calculating BGC-level MIBiG identity summaries...")
    hits_only = merged_genes[merged_genes["pident"] > 0]
    bgc_novelty = hits_only.groupby(["genome_id", "bgc_id"])["pident"].mean().reset_index()
    bgc_novelty.rename(columns={"pident": "avg_mibig_identity"}, inplace=True)

    all_bgcs = genes_df[["genome_id", "bgc_id"]].drop_duplicates()
    bgc_novelty = pd.merge(all_bgcs, bgc_novelty, on=["genome_id", "bgc_id"], how="left")
    bgc_novelty["avg_mibig_identity"] = bgc_novelty["avg_mibig_identity"].fillna(0)

    if "bgc_id" not in bgc_metadata.columns and "bgc_candidate_id" in bgc_metadata.columns:
        bgc_metadata = bgc_metadata.rename(columns={"bgc_candidate_id": "bgc_id"})

    final_bgc_table = pd.merge(
        bgc_novelty, bgc_metadata, on=["genome_id", "bgc_id"], how="inner"
    )
    score_col = "deepbgc_score" if "deepbgc_score" in final_bgc_table.columns else "score"

    confident = final_bgc_table[score_col] >= args.min_deepbgc_score
    community_atlas = final_bgc_table[
        confident & (final_bgc_table["avg_mibig_identity"] >= args.known_identity_threshold)
    ]
    discovery_zone = final_bgc_table[
        confident & (final_bgc_table["avg_mibig_identity"] < args.known_identity_threshold)
    ]

    community_atlas.to_csv(output_dir / "community_atlas.csv", index=False)
    discovery_zone.to_csv(output_dir / "discovery_zone.csv", index=False)

    print(f"Total BGCs processed: {len(final_bgc_table)}")
    print(f"Community atlas: {len(community_atlas)} BGCs")
    print(f"Discovery zone: {len(discovery_zone)} BGCs")


if __name__ == "__main__":
    main()
